# Generated by Django 6.0.3 on 2026-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_location", models.CharField()),
                ("first_unit", models.CharField()),
                ("first_port", models.CharField()),
                ("second_location", models.CharField()),
                ("second_unit", models.CharField()),
                ("second_port", models.CharField()),
            ],
        ),
    ]
