# Generated by Django 6.0.3 on 2026-05-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_location", models.CharField()),
                ("first_unit", models.CharField()),
                ("first_port", models.CharField()),
                ("second_location", models.CharField()),
                ("second_unit", models.CharField()),
                ("second_port", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("location", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField()),
                ("line_name", models.CharField()),
                ("port", models.CharField()),
                ("unit", models.CharField()),
                ("chan", models.CharField()),
            ],
            options={
                "unique_together": {("location", "line_name", "port", "unit", "chan")},
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField()),
                (
                    "parent_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="Lines.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lines.point"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lines.route"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("route", "order")},
            },
        ),
        migrations.AddField(
            model_name="route",
            name="points",
            field=models.ManyToManyField(through="Lines.RoutePoint", to="Lines.point"),
        ),
        migrations.AddField(
            model_name="route",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="Lines.service",
            ),
        ),
    ]
