# Generated by Django 6.0.3 on 2026-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.CharField()),
                ("location", models.CharField()),
                ("role", models.CharField()),
            ],
        ),
    ]
